<?php


function ajax_login_form_user_login_form_alter (&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {



    $form['system_messages'] = [
        '#markup' => '<div id="box">123</div>',
        '#weight' => -100,
    ];
    $form['actions']['submit']['#ajax'] = [
        'callback' => 'Drupal\ajax_login\MyAjaxLogin\MyAjaxLogin::MyAjaxSubmit',
        'wrapper' => 'box',
        'event' => 'click',
        'progress' => [
            'type' => 'throbber',
        ],
    ];

}

