<?php

/**
 * @file
 */
use Drupal\Core\Render\BubbleableMetadata;

/**
 * Implements hook_mail().
 */
function dispatch_module_mail($key, &$message, $params) {
  switch ($key) {
    case 'email_dispatch':

      $message['subject'] = t('Email from phpmodule2.test');
      $message['body'][] =
        t('@message', [
          '@message' => $params['message'],
        ]);
      break;
  }
}

/**
 * Implements hook_token_info().
 */
function dispatch_module_token_info() {
  $type = [
    'name' => t('Dispatch'),
    'description' => t('Dispatch token'),
  ];
  $username['username'] = [
    'name' => t('Username'),
    'description' => t('User name'),
  ];
  $site_email['site_email'] = [
    'name' => t('Site email'),
    'description' => t('Site email'),
  ];
  return [
    'types' => ['dispatch' => $type],
    'tokens' => [
      'dispatch' => [
        'username' => $username['username'],
        'site_email' => $site_email['site_email'],
      ],
    ],
  ];
}

/**
 * Implements hook_tokens().
 */
function dispatch_module_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];
  $site_config = \Drupal::config('system.site');
  $site_email = $site_config->get('mail');
  foreach ($tokens as $name => $original) {
    switch ($name) {
      case 'username':
        $replacements[$original] = $username;
        break;

      case 'site_email':
        $replacements[$original] = $site_email;
        break;
    }
  }
  return $replacements;
}
